#!/usr/bin/env node
/**
 * Anvesh Setup — lightweight installer / local stack runner.
 */
import { spawn, type ChildProcess } from "node:child_process";
import { openSync, closeSync } from "node:fs";
import { mkdir, writeFile, access, readFile, unlink, chmod } from "node:fs/promises";
import path from "node:path";
import { randomBytes } from "node:crypto";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function usage(): never {
  console.log(`Anvesh Setup — easy local bootstrap — by VaagaTech

Usage:
  anvesh-setup init [--dir .]     Create .anvesh layout, .env, and starter configs
  anvesh-setup up [--dir .]       Start engine + hub + spider + indexer (one command)
  anvesh-setup down [--dir .]     Stop processes started by up
  anvesh-setup doctor             Check Node version and key paths
  anvesh-setup print-services     Show how to run each application instance

Tip: from the monorepo root after build:
  npm run stack
`);
  process.exit(1);
}

function parseArgs(argv: string[]) {
  const cmd = argv[0] || "help";
  const dirIdx = argv.indexOf("--dir");
  const dir = dirIdx >= 0 && argv[dirIdx + 1] ? argv[dirIdx + 1]! : process.cwd();
  return { cmd, dir: path.resolve(dir) };
}

async function exists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

async function loadEnvFile(envPath: string): Promise<Record<string, string>> {
  if (!(await exists(envPath))) return {};
  const text = await readFile(envPath, "utf8");
  const out: Record<string, string> = {};
  for (const line of text.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq < 0) continue;
    out[t.slice(0, eq)] = t.slice(eq + 1);
  }
  return out;
}

function applyEnv(vars: Record<string, string>): void {
  for (const [k, v] of Object.entries(vars)) {
    if (process.env[k] === undefined) process.env[k] = v;
  }
}

/** Resolve monorepo root (workspaces) or package install parent. */
async function resolveRepoRoot(start: string): Promise<string> {
  let cur = start;
  for (let i = 0; i < 8; i++) {
    const pkg = path.join(cur, "package.json");
    if (await exists(pkg)) {
      try {
        const j = JSON.parse(await readFile(pkg, "utf8")) as {
          workspaces?: unknown;
          name?: string;
        };
        if (j.workspaces || j.name === "@vaagatech/anvesh-monorepo") return cur;
      } catch {
        /* continue */
      }
    }
    const parent = path.dirname(cur);
    if (parent === cur) break;
    cur = parent;
  }
  // setup package lives at apps/setup — monorepo is ../..
  const fromSetup = path.resolve(__dirname, "../../..");
  if (await exists(path.join(fromSetup, "apps/engine"))) return fromSetup;
  return start;
}

async function init(root: string): Promise<void> {
  const anvesh = path.join(root, ".anvesh");
  await mkdir(path.join(anvesh, "data"), { recursive: true });
  await mkdir(path.join(anvesh, "hub"), { recursive: true });
  await mkdir(path.join(anvesh, "crawl"), { recursive: true });
  await mkdir(path.join(anvesh, "configs"), { recursive: true });
  await mkdir(path.join(anvesh, "logs"), { recursive: true });

  const envPath = path.join(root, ".env.anvesh");
  if (!(await exists(envPath))) {
    const adminPass = randomBytes(18).toString("base64url");
    const hubSecretsKey = randomBytes(32).toString("base64");
    const engineKey = randomBytes(24).toString("base64url");
    const spiderKey = randomBytes(24).toString("base64url");
    const indexerKey = randomBytes(24).toString("base64url");
    const env = `# Generated by anvesh-setup — VaagaTech
ANVESH_SECURE=1
ANVESH_STORAGE=filesystem
ANVESH_DATA_DIR=.anvesh/data
ANVESH_PORT=3848
ANVESH_HUB_PORT=3849
ANVESH_HUB_DATA=.anvesh/hub
ANVESH_HUB_ADMIN_USER=admin
ANVESH_HUB_ADMIN_PASSWORD=${adminPass}
ANVESH_HUB_SECRETS_KEY=${hubSecretsKey}
ANVESH_API_KEY=${engineKey}
ANVESH_SPIDER_API_KEY=${spiderKey}
ANVESH_INDEXER_API_KEY=${indexerKey}
ANVESH_SPIDER_PORT=3851
ANVESH_INDEXER_PORT=3852
ANVESH_LOG_PRETTY=1
`;
    await writeFile(envPath, env, { mode: 0o600 });
    try {
      await chmod(envPath, 0o600);
    } catch {
      /* best effort */
    }
  }

  const spiderCfg = {
    seeds: ["https://example.com/"],
    maxPages: 50,
    maxDepth: 3,
    outputPath: ".anvesh/crawl/out.jsonl",
    roles: [{ name: "guest", anonymous: true }],
  };
  await writeFile(
    path.join(anvesh, "configs", "spider.default.json"),
    JSON.stringify(spiderCfg, null, 2) + "\n",
    "utf8",
  );

  const readme = `# Anvesh local stack

Generated by \`anvesh-setup init\`.

## One command

\`\`\`bash
set -a; source .env.anvesh; set +a
npm run stack          # or: anvesh-setup up
\`\`\`

Open Hub at http://127.0.0.1:3849 — login admin (password in .env.anvesh).
Local engine / spider / indexer instances are registered automatically with API keys from .env.anvesh.

Stop with: \`npm run stack:down\`
`;
  await writeFile(path.join(anvesh, "README.md"), readme, "utf8");

  console.log(`Anvesh setup complete in ${root}

Created:
  .anvesh/data          engine indexes
  .anvesh/hub           hub RBAC state
  .anvesh/crawl         spider output
  .anvesh/configs       starter spider config
  .env.anvesh           environment (credentials — chmod 600)

Next:
  set -a; source .env.anvesh; set +a
  npm run stack
`);
}

type PidMap = Record<string, number>;

async function readPids(root: string): Promise<PidMap> {
  const p = path.join(root, ".anvesh", "pids.json");
  if (!(await exists(p))) return {};
  try {
    return JSON.parse(await readFile(p, "utf8")) as PidMap;
  } catch {
    return {};
  }
}

async function writePids(root: string, pids: PidMap): Promise<void> {
  await mkdir(path.join(root, ".anvesh"), { recursive: true });
  await writeFile(path.join(root, ".anvesh", "pids.json"), JSON.stringify(pids, null, 2) + "\n");
}

async function waitHealthy(url: string, label: string, timeoutMs = 45000): Promise<void> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    try {
      const res = await fetch(url);
      if (res.ok) {
        console.log(`  ✓ ${label} ready (${url})`);
        return;
      }
    } catch {
      /* retry */
    }
    await new Promise((r) => setTimeout(r, 400));
  }
  throw new Error(`${label} did not become healthy at ${url} within ${timeoutMs}ms`);
}

function spawnService(
  name: string,
  nodeArgs: string[],
  cwd: string,
  logPath: string,
  env: NodeJS.ProcessEnv,
): ChildProcess {
  const logFd = openSync(logPath, "a");
  const out = spawn("node", nodeArgs, {
    cwd,
    env,
    detached: true,
    // Own fds so children survive when the setup CLI / npm exits.
    stdio: ["ignore", logFd, logFd],
  });
  // Child owns the fd after spawn; close our copy.
  try {
    closeSync(logFd);
  } catch {
    /* ok */
  }
  out.unref();
  console.log(`  → started ${name} (pid ${out.pid}) → ${logPath}`);
  return out;
}

async function up(root: string): Promise<void> {
  if (!(await exists(path.join(root, ".env.anvesh")))) {
    console.log("No .env.anvesh — running init first…");
    await init(root);
  }
  const envFile = await loadEnvFile(path.join(root, ".env.anvesh"));
  applyEnv(envFile);

  const engineCli = path.join(root, "apps/engine/dist/cli.js");
  const hubCli = path.join(root, "apps/hub/dist/server/cli.js");
  const spiderCli = path.join(root, "apps/spider/dist/cli.js");
  const indexerCli = path.join(root, "apps/indexer/dist/cli.js");

  for (const [label, p] of [
    ["engine", engineCli],
    ["hub", hubCli],
    ["spider", spiderCli],
    ["indexer", indexerCli],
  ] as const) {
    if (!(await exists(p))) {
      throw new Error(
        `Missing ${label} build at ${p}. Run: npm run build  (from ${root})`,
      );
    }
  }

  const existing = await readPids(root);
  if (Object.keys(existing).length) {
    console.log("Existing pids found — stopping previous stack first…");
  } else {
    console.log("Clearing any orphan listeners on Anvesh ports…");
  }
  await down(root);

  await mkdir(path.join(root, ".anvesh/logs"), { recursive: true });
  const childEnv = { ...process.env, ...envFile, ANVESH_LOG_PRETTY: "0" };

  console.log("Starting Anvesh stack…");
  const children: PidMap = {};
  const engine = spawnService(
    "engine",
    [engineCli, "serve"],
    root,
    path.join(root, ".anvesh/logs/engine.log"),
    childEnv,
  );
  const hub = spawnService(
    "hub",
    [hubCli],
    root,
    path.join(root, ".anvesh/logs/hub.log"),
    childEnv,
  );
  const spider = spawnService(
    "spider",
    [spiderCli, "serve"],
    root,
    path.join(root, ".anvesh/logs/spider.log"),
    childEnv,
  );
  const indexer = spawnService(
    "indexer",
    [indexerCli, "serve"],
    root,
    path.join(root, ".anvesh/logs/indexer.log"),
    childEnv,
  );

  if (engine.pid) children.engine = engine.pid;
  if (hub.pid) children.hub = hub.pid;
  if (spider.pid) children.spider = spider.pid;
  if (indexer.pid) children.indexer = indexer.pid;
  await writePids(root, children);

  const enginePort = envFile.ANVESH_PORT ?? "3848";
  const hubPort = envFile.ANVESH_HUB_PORT ?? "3849";
  const spiderPort = envFile.ANVESH_SPIDER_PORT ?? "3851";
  const indexerPort = envFile.ANVESH_INDEXER_PORT ?? "3852";

  await waitHealthy(`http://127.0.0.1:${enginePort}/health`, "engine");
  await waitHealthy(`http://127.0.0.1:${hubPort}/hub/health`, "hub");
  await waitHealthy(`http://127.0.0.1:${spiderPort}/health`, "spider");
  await waitHealthy(`http://127.0.0.1:${indexerPort}/health`, "indexer");

  for (const [name, pid] of Object.entries(children)) {
    if (!isAlive(pid)) {
      throw new Error(
        `${name} (pid ${pid}) exited after start — check .anvesh/logs/${name}.log`,
      );
    }
  }

  const user = envFile.ANVESH_HUB_ADMIN_USER ?? "admin";

  console.log(`
Anvesh is up.

  Hub UI     http://127.0.0.1:${hubPort}
  Login      ${user} (password in .env.anvesh)
  Engine     http://127.0.0.1:${enginePort}
  Spider     http://127.0.0.1:${spiderPort}
  Indexer    http://127.0.0.1:${indexerPort}

  Logs       .anvesh/logs/
  Stop       npm run stack:down

Happy path:
  1. Open Hub → Indexes → create "web" (vector dims 256 is default)
  2. Spider → run a crawl (auto-index on)
  3. Search → keyword or hybrid with plain text (local embeddings)
  Or: npm run demo:seed  then search index "demo"
`);
}

async function down(root: string, ports?: string[]): Promise<void> {
  const pids = await readPids(root);
  for (const [name, pid] of Object.entries(pids)) {
    try {
      process.kill(pid, "SIGTERM");
      console.log(`  stopped ${name} (pid ${pid})`);
    } catch {
      console.log(`  ${name} pid ${pid} already gone`);
    }
  }
  await new Promise((r) => setTimeout(r, 400));
  for (const pid of Object.values(pids)) {
    try {
      process.kill(pid, "SIGKILL");
    } catch {
      /* ok */
    }
  }
  try {
    await unlink(path.join(root, ".anvesh", "pids.json"));
  } catch {
    /* ok */
  }

  // Free default ports in case orphan processes still hold them.
  const envFile = await loadEnvFile(path.join(root, ".env.anvesh"));
  const toFree =
    ports ??
    [
      envFile.ANVESH_PORT ?? "3848",
      envFile.ANVESH_HUB_PORT ?? "3849",
      envFile.ANVESH_SPIDER_PORT ?? "3851",
      envFile.ANVESH_INDEXER_PORT ?? "3852",
    ];
  for (const port of toFree) {
    await freePort(port);
  }
  console.log("Stack stopped.");
}

function isAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

async function freePort(port: string): Promise<void> {
  try {
    const { execFile } = await import("node:child_process");
    const { promisify } = await import("node:util");
    const execFileAsync = promisify(execFile);
    const { stdout } = await execFileAsync("lsof", ["-ti", `tcp:${port}`], {
      encoding: "utf8",
    }).catch(() => ({ stdout: "" }));
    const pids = stdout
      .split("\n")
      .map((s) => s.trim())
      .filter(Boolean);
    for (const pid of pids) {
      try {
        process.kill(Number(pid), "SIGTERM");
        console.log(`  freed :${port} (pid ${pid})`);
      } catch {
        /* ok */
      }
    }
    if (pids.length) await new Promise((r) => setTimeout(r, 300));
    for (const pid of pids) {
      try {
        process.kill(Number(pid), "SIGKILL");
      } catch {
        /* ok */
      }
    }
  } catch {
    /* lsof missing — ignore */
  }
}

async function doctor(root: string): Promise<void> {
  const major = Number(process.versions.node.split(".")[0]);
  console.log(`Node.js ${process.version} ${major >= 20 ? "OK" : "NEED >= 20"}`);
  for (const p of [".anvesh", ".anvesh/data", ".anvesh/hub", ".env.anvesh"]) {
    const full = path.join(root, p);
    try {
      await access(full);
      console.log(`OK  ${p}`);
    } catch {
      console.log(`MISS ${p}  (run: anvesh-setup init)`);
    }
  }
}

function printServices(): void {
  console.log(`Anvesh applications

  One command (preferred):
    npm run stack

  Or separately:
    Engine   :3848   npx anvesh-engine serve
    Hub      :3849   npx anvesh-hub
    Spider   :3851   npx anvesh-spider serve
    Indexer  :3852   npx anvesh-indexer serve

Hub auto-registers local instance URLs on first boot.
`);
}

async function main(): Promise<void> {
  const { cmd, dir } = parseArgs(process.argv.slice(2));
  const root = await resolveRepoRoot(dir);
  if (cmd === "init") await init(root);
  else if (cmd === "up") await up(root);
  else if (cmd === "down") await down(root);
  else if (cmd === "doctor") await doctor(root);
  else if (cmd === "print-services") printServices();
  else usage();
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
