#!/usr/bin/env node
/**
 * Anvesh Setup — lightweight installer / scaffold for local multi-app stacks.
 */
import { mkdir, writeFile, access } from "node:fs/promises";
import path from "node:path";
import { randomBytes } from "node:crypto";

function usage(): never {
  console.log(`Anvesh Setup — easy local bootstrap — by VaagaTech

Usage:
  anvesh-setup init [--dir .]     Create .anvesh layout, .env, and starter configs
  anvesh-setup doctor             Check Node version and key paths
  anvesh-setup print-services     Show how to run each application instance

This tool stays simple: it writes files and prints commands. It does not download binaries.
`);
  process.exit(1);
}

function parseArgs(argv: string[]) {
  const cmd = argv[0] || "help";
  const dirIdx = argv.indexOf("--dir");
  const dir = dirIdx >= 0 && argv[dirIdx + 1] ? argv[dirIdx + 1]! : process.cwd();
  return { cmd, dir: path.resolve(dir) };
}

async function init(root: string): Promise<void> {
  const anvesh = path.join(root, ".anvesh");
  await mkdir(path.join(anvesh, "data"), { recursive: true });
  await mkdir(path.join(anvesh, "hub"), { recursive: true });
  await mkdir(path.join(anvesh, "crawl"), { recursive: true });
  await mkdir(path.join(anvesh, "configs"), { recursive: true });

  const adminPass = randomBytes(6).toString("base64url");
  const envPath = path.join(root, ".env.anvesh");
  const env = `# Generated by anvesh-setup — VaagaTech
ANVESH_STORAGE=filesystem
ANVESH_DATA_DIR=.anvesh/data
ANVESH_PORT=3848
ANVESH_HUB_PORT=3849
ANVESH_HUB_DATA=.anvesh/hub
ANVESH_HUB_ADMIN_USER=admin
ANVESH_HUB_ADMIN_PASSWORD=${adminPass}
ANVESH_SPIDER_PORT=3851
ANVESH_INDEXER_PORT=3852
ANVESH_LOG_PRETTY=1
`;
  await writeFile(envPath, env, "utf8");

  const spiderCfg = {
    seeds: ["https://example.com/"],
    maxPages: 50,
    maxDepth: 3,
    outputPath: ".anvesh/crawl/out.jsonl",
    roles: [{ name: "guest", anonymous: true }],
  };
  await writeFile(
    path.join(anvesh, "configs", "spider.default.json"),
    JSON.stringify(spiderCfg, null, 2) + "\n",
    "utf8",
  );

  const readme = `# Anvesh local stack

Generated by \`anvesh-setup init\`.

## Start (separate terminals)

\`\`\`bash
set -a; source .env.anvesh; set +a

# 1) Engine
npx anvesh-engine serve
# or: npm run start:engine

# 2) Hub control plane
npx anvesh-hub
# open http://127.0.0.1:3849
# login admin / (see ANVESH_HUB_ADMIN_PASSWORD in .env.anvesh)

# 3) Optional workers for multi-instance Hub control
npx anvesh-spider serve
npx anvesh-indexer serve
\`\`\`

Then in Hub → Instances, register:
- engine http://127.0.0.1:3848
- spider http://127.0.0.1:3851
- indexer http://127.0.0.1:3852
`;
  await writeFile(path.join(anvesh, "README.md"), readme, "utf8");

  console.log(`Anvesh setup complete in ${root}

Created:
  .anvesh/data          engine indexes
  .anvesh/hub           hub RBAC state
  .anvesh/crawl         spider output
  .anvesh/configs       starter spider config
  .env.anvesh           environment (admin password included)

Next:
  set -a; source .env.anvesh; set +a
  anvesh-setup print-services
`);
}

async function doctor(root: string): Promise<void> {
  const major = Number(process.versions.node.split(".")[0]);
  console.log(`Node.js ${process.version} ${major >= 20 ? "OK" : "NEED >= 20"}`);
  for (const p of [".anvesh", ".anvesh/data", ".anvesh/hub", ".env.anvesh"]) {
    const full = path.join(root, p);
    try {
      await access(full);
      console.log(`OK  ${p}`);
    } catch {
      console.log(`MISS ${p}  (run: anvesh-setup init)`);
    }
  }
}

function printServices(): void {
  console.log(`Anvesh applications (run multiple instances freely)

  Engine   :3848   npx anvesh-engine serve
  Hub      :3849   npx anvesh-hub
  Spider   :3851   npx anvesh-spider serve
  Indexer  :3852   npx anvesh-indexer serve

Hub is the control plane: register each instance URL, manage indexes,
spider/indexer configs, and RBAC users (admin / operator / viewer).

Load env first:
  set -a; source .env.anvesh; set +a
`);
}

async function main(): Promise<void> {
  const { cmd, dir } = parseArgs(process.argv.slice(2));
  if (cmd === "init") await init(dir);
  else if (cmd === "doctor") await doctor(dir);
  else if (cmd === "print-services") printServices();
  else usage();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
