# Anvesh documentation site (GitHub Pages)
title: Anvesh Docs
description: Cloud-Native Search Engine & Vector Database by VaagaTech
url: "https://vaagatech.github.io/anvesh"
baseurl: "/anvesh"

author:
  name: VaagaTech
  email: info@vaagatech.com
  url: https://www.vaagatech.com

repository: vaagatech/anvesh
license: MIT

markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

defaults:
  - scope:
      path: ""
    values:
      layout: default
